### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by bdthanh** [AY2223S1-CS2113-W12-1/tp#50] opened 2022-10-11 04:49 UTC
All of our changes at some point where lost because someone overwrote it unintentionally with their merge commit and tbh this is not workable with(especially since we're ignoring the forking workflow and largely not doing PR reviews)

TLDR: Can we all ensure to pull the latest code right before merging any PR with `git pull upstream master` **even if it shows no conflicts**
- Pulling at the start is not sufficient - do it right before a merge(clicking on merge PR) as well

_Originally posted by @winston-lim in https://github.com/AY2223S1-CS2113-W12-1/tp/pull/47#pullrequestreview-1136738757_

**Comment by winston-lim** [comment] 2022-10-16 09:44
## Responsibility of CI tests should be on PR creator
As I was creating my PR I realised that there were too many changes by others that cause errors and warnings by both the compiler and Checkstyle.  This is a problem because these errors cause CI tests to fail i.e. we have some build error caused by our own changes and so the responsibility lies with the PR creator to fix this. If we each do not check our own, then someone else has to fix all of the errors(i think Bui has been helping to do this) which isn't fair and is a waste of dev time.
- For the Checkstyle warnings, you may ignore "missing javadoc" warnings ONLY - the rest will CI checks to fail
- For example, we have some code that has lines > 100 characters in multiple files and we have some files that have no spaces before entering a new block e.g. `if (condition){`
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/64213369/196027456-0a93c122-f721-4aa8-94b7-f666224473e2.png">

## Suggested PR workflow
Given that we are skipping the forking workflow and not proper code reviews, it is a good idea for us to make sure we are submitting code of sufficient quality. This means that at the very minimum we should ensure that our PR passes the CI tests before clicking on merge.
For subsequent milestones after 1.5, I suggest we follow this workflow.

### 1. Starting out
- `git checkout master` to ensure you are at master branch
- `git pull upstream master` to ensure you have latest code from upstream
- `git checkout -b <branchName>` to create a branch locally and switch to that branch
- Work on whatever you want to work on
- After finishing your work, ensure you are in project directory i.e. `tp` then run `checkstyle **/*.java` to check for all errors
- Fix any errors that are not related to JavaDocs
- `git add ...` to stage all your changes
- `git commit ...` to  commit all your changes
- `git push -u origin <branch_name>` to push your new branch to your fork(origin) and track it

### 2. Before creating PR
- Check if someone else's PR is open. If there is another open PR, wait for it to close - he is probably fixing errors and waiting for CI tests to pass before merging.
  - Creating a PR before he merges just wastes time
- If no PR is open, then:
  -  Run `git pull upstream master` to pull the latest changes in case someone else has merged to upstream before you create your PR
  - If already at latest change, move to step 3. Otherwise:
  - Resolve any merge conflicts
  - Push your branch once again to your fork with `git push`
  - Create a PR from your branch in origin (forkName/<branch_name>) to upstream(AY2223S1-CS2113-W12-1/master)

### 3. After creating a PR
- Wait for all CI tests to pass
- If CI test passes, move to step 4. Otherwise:
- Fix any parts of your code if the CI tests fails, and push the fixes
- Continue this process until all CI test passes

### 4. Before clicking merge PR
- By now all CI tests based on your changes should have passed
- Click merge PR

**Closed** 2022-10-27 20:25 UTC
